### ISSUE TITLE
你好，请问您可以提供测试集给我用于测试么？

### ISSUE THREAD

**Issue by StriveStruggleYou** [zle1992/2017-Big-Data-Challenge#1]
我对这个比赛很感兴趣，可惜之前没有关注到这个比赛，但是没有数据对我自己的想法验证，感觉完整的测试数据集很重要，如果您不嫌弃麻烦的话，可以发送给我吗？谢谢大佬。

**Comment by zle1992** [comment]
测试集是线上才有的，我也木有的。不过之前线上测试的结果F1在0.96以上我记得。

**Comment by StriveStruggleYou** [comment]
我说的是初赛的测试集也没有么？您不是说上传了部分么？

**Comment by zle1992** [comment]
测试集 没有label 你也没办法验证的。

**Comment by StriveStruggleYou** [comment]
我估计会自己标注一下，还要找一些人来帮帮忙才行。

**Comment by zle1992** [comment]
这个比较难标注的，单看数据看不出来。
链接：https://pan.baidu.com/s/14dCrA7V2oNHOzmKyakVC9Q 
提取码：79px

**Comment by StriveStruggleYou** [comment]
好的非常感谢大佬，我已经搞出可视化的模型了，这些眼睛过一遍还是可以标注的把哈哈哈。

**Comment by StriveStruggleYou** [comment]
我们都是曼巴粉哈哈，等我搞出来，你来杭州我请你吃饭嘿嘿。

**Comment by zle1992** [comment]
好的。祝你好运
